### PR TITLE
Static framework privacy file podspec fix

### PR DESCRIPTION
**Pull request by anton-plebanovich**
Please check https://github.com/devicekit/DeviceKit/pull/397 which implements the same fix

### CODE REVIEW

**Comment by iveloff-developer** [comment]
@anton-plebanovich 
Good catch, you help me a lot!

**Comment by anton-plebanovich** [comment]
@tikhop Sorry to bother but please review and release a hotfix when you have available time

**Review by tikhop — APPROVED** [review]

**Comment by tikhop** [comment]
Hello @anton-plebanovich, thanks for bringing this up and I'm sorry for the delay in response.

I've merged the PR and I'm going to make a release asap. 

Thanks again!

**Comment by tikhop** [comment]
Hi @anton-plebanovich, I've released the new version (1.2.7). Thank you!

**Pull request merged**
